#!/usr/bin/env python3
"""Build wordbank.js — large, frequency-ordered English→Japanese decks.

Data sources (both fetched at build time):
  * EJDict (kujirahand/EJDict) — Public Domain English-Japanese dictionary.
  * google-10000-english (first20hours) — English words by usage frequency.

The generated `wordbank.js` defines `WORDBANK`, an array of deck objects of the
same shape as presets.js, sliced into 500-word frequency tiers.

Run:  python3 tools/build_wordbank.py
"""
import glob
import json
import os
import re
import subprocess
import tempfile
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'wordbank.js')
TIER = 500  # words per deck

EJDICT_TAR = 'https://codeload.github.com/kujirahand/EJDict/tar.gz/refs/heads/master'
FREQ_URL = 'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt'

JP = re.compile(r'[぀-ヿ㐀-鿿]')  # hiragana/katakana/kanji


def fetch(url, path):
    with urllib.request.urlopen(url, timeout=60) as r, open(path, 'wb') as f:
        f.write(r.read())


def load_dict(workdir):
    tar = os.path.join(workdir, 'ej.tar.gz')
    fetch(EJDICT_TAR, tar)
    subprocess.run(['tar', 'xzf', tar, '-C', workdir], check=True)
    d = {}
    for f in glob.glob(os.path.join(workdir, 'EJDict-master', 'src', '?.txt')):
        for line in open(f, encoding='utf-8'):
            if '\t' not in line:
                continue
            w, defi = line.rstrip('\n').split('\t', 1)
            d[w.lower().strip()] = defi.strip()
    return d


def clean_fallback(s):
    s = s.split(' / ')[0]
    s = re.sub(r'《[^》]*》', '', s)
    s = re.sub(r'〈[^〉]*〉', '', s)
    s = re.sub(r'\([^)]*\)', '', s)
    s = re.sub(r'〔[^〕]*〕', '', s)
    s = re.sub(r'[＝=].*$', '', s)
    return s.strip(' ,;・。')[:24]


def gloss(defi):
    """Extract a concise Japanese gloss. Returns None if unusable."""
    if not defi or defi[0] in '=＝':
        return None
    core = []
    for m in re.findall(r'『(.+?)』', defi):
        m = m.strip()
        if m and m not in core:
            core.append(m)
    out = '／'.join(core[:3]) if core else clean_fallback(defi)
    if not out or not JP.search(out):  # 日本語を含まないものは除外
        return None
    return out


def main():
    with tempfile.TemporaryDirectory() as wd:
        d = load_dict(wd)
        freq_path = os.path.join(wd, 'freq.txt')
        fetch(FREQ_URL, freq_path)
        freq = [w.strip().lower() for w in open(freq_path, encoding='utf-8') if w.strip()]

    pairs, seen = [], set()
    for w in freq:
        if not re.fullmatch(r'[a-z]{2,}', w) or w in seen:
            continue
        g = d.get(w)
        if not g:
            continue
        gl = gloss(g)
        if not gl:
            continue
        seen.add(w)
        pairs.append([w, gl])

    decks = []
    for i in range(0, len(pairs), TIER):
        chunk = pairs[i:i + TIER]
        lo, hi = i + 1, i + len(chunk)
        decks.append({
            'id': f'en-freq-{lo}',
            'name': f'英単語 頻出 {lo}〜{hi}',
            'emoji': '🔤',
            'lang': 'en-US',
            'desc': f'使用頻度 {lo}〜{hi} 位',
            'cards': chunk,
        })

    body = json.dumps(decks, ensure_ascii=False, separators=(',', ':'))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* wordbank.js — auto-generated by tools/build_wordbank.py\n')
        f.write(' * Source: EJDict (Public Domain) + google-10000-english (frequency).\n')
        f.write(f' * {len(pairs)} words across {len(decks)} frequency tiers. Do not edit by hand. */\n')
        f.write('const WORDBANK = ' + body + ';\n')
    print(f'Wrote {OUT}: {len(pairs)} words, {len(decks)} decks')


if __name__ == '__main__':
    main()
