#!/usr/bin/env python3
"""Build wordbank.js — large, frequency-ordered English→Japanese decks.

Data sources (both fetched at build time):
  * EJDict (kujirahand/EJDict) — Public Domain English-Japanese dictionary.
  * google-10000-english (first20hours) — English words by usage frequency.

The generated `wordbank.js` defines `WORDBANK`, an array of deck objects of the
same shape as presets.js, sliced into 500-word frequency tiers.

Run:  python3 tools/build_wordbank.py
"""
import glob
import json
import os
import re
import subprocess
import tempfile
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'wordbank.js')
TIER = 500  # words per deck

EJDICT_TAR = 'https://codeload.github.com/kujirahand/EJDict/tar.gz/refs/heads/master'
FREQ_URL = 'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english.txt'

JP = re.compile(r'[぀-ヿ㐀-鿿]')  # hiragana/katakana/kanji

# 機能語（冠詞・前置詞・代名詞・助動詞・be動詞など）は学習価値が低いので除外する
STOPWORDS = set("""
the of and to a in that is was for it with as his on be at by i this had not are but from
or have an they which you were her all she there would their we him been has when who will
more no if out so up said what its about into than them can only other do may after most
such my your our these am does did between just him your should under while because each
those then now very also any our us how here our own through where why both being into
he she it we they you me him her us them my your his its our their mine yours hers ours theirs
am is are was were be been being do does did have has had will would shall should can could
may might must ought a an the this that these those of in on at by for with about against
between into through during before after above below to from up down out off over under
and but or nor so yet for as if than because while although though unless until whether
i you he she it we they who whom whose which what
""".split())


def fetch(url, path):
    with urllib.request.urlopen(url, timeout=60) as r, open(path, 'wb') as f:
        f.write(r.read())


def load_dict(workdir):
    tar = os.path.join(workdir, 'ej.tar.gz')
    fetch(EJDICT_TAR, tar)
    subprocess.run(['tar', 'xzf', tar, '-C', workdir], check=True)
    d = {}
    for f in glob.glob(os.path.join(workdir, 'EJDict-master', 'src', '?.txt')):
        for line in open(f, encoding='utf-8'):
            if '\t' not in line:
                continue
            w, defi = line.rstrip('\n').split('\t', 1)
            d[w.lower().strip()] = defi.strip()
    return d


def tidy(term):
    """1語義ぶんのノイズ（記号・注記・ふりがな）を除去して簡潔にする。"""
    term = re.split(r'[;；]', term)[0]          # 「;」以降の補足は捨てる
    term = re.sub(r'《[^》]*》', '', term)
    term = re.sub(r'〈[^〉]*〉', '', term)
    term = re.sub(r'[（(][^）)]*[）)]', '', term)  # （…）注記
    term = re.sub(r'[\[［][^\]］]*[\]］]', '', term)  # ［…］注記
    term = re.sub(r'〔[^〕]*〕', '', term)
    term = re.sub(r'[＝=].*$', '', term)
    term = term.replace('…', '').strip(' ,，、。・~～:：')
    return term


def gloss(defi):
    """Extract a concise Japanese gloss (1〜2語義). Returns None if unusable."""
    if not defi or defi[0] in '=＝':
        return None
    # 品詞略号など、語義として無意味な断片
    POS_JUNK = set('名動形副代接前数助他自補冠') | {'する', 'の', 'こと'}
    terms = []
    src = re.findall(r'『(.+?)』', defi) or re.split(r'\s*/\s*', defi)
    for m in src:
        t = tidy(m)
        if t and JP.search(t) and t not in terms and t not in POS_JUNK and len(t) <= 16:
            terms.append(t)
        if len(terms) >= 2:
            break
    if not terms:
        return None
    return '／'.join(terms)


def main():
    with tempfile.TemporaryDirectory() as wd:
        d = load_dict(wd)
        freq_path = os.path.join(wd, 'freq.txt')
        fetch(FREQ_URL, freq_path)
        freq = [w.strip().lower() for w in open(freq_path, encoding='utf-8') if w.strip()]

    pairs, seen = [], set()
    for w in freq:
        if not re.fullmatch(r'[a-z]{2,}', w) or w in seen or w in STOPWORDS:
            continue
        g = d.get(w)
        if not g:
            continue
        gl = gloss(g)
        if not gl:
            continue
        seen.add(w)
        pairs.append([w, gl])

    decks = []
    for i in range(0, len(pairs), TIER):
        chunk = pairs[i:i + TIER]
        lo, hi = i + 1, i + len(chunk)
        decks.append({
            'id': f'en-freq-{lo}',
            'name': f'英単語 頻出 {lo}〜{hi}',
            'emoji': '🔤',
            'lang': 'en-US',
            'desc': f'使用頻度 {lo}〜{hi} 位',
            'cards': chunk,
        })

    body = json.dumps(decks, ensure_ascii=False, separators=(',', ':'))
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('/* wordbank.js — auto-generated by tools/build_wordbank.py\n')
        f.write(' * Source: EJDict (Public Domain) + google-10000-english (frequency).\n')
        f.write(f' * {len(pairs)} words across {len(decks)} frequency tiers. Do not edit by hand. */\n')
        f.write('const WORDBANK = ' + body + ';\n')
    print(f'Wrote {OUT}: {len(pairs)} words, {len(decks)} decks')


if __name__ == '__main__':
    main()
